name = "symbaroum"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = ".svelte-kit/cloudflare/_worker.js"

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "npm run build"
pages_build_output_dir = ".svelte-kit/cloudflare"

[build.upload]
format = "service-worker"
