name = "symbaroum"
compatibility_date = "2024-02-13"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = ".svelte-kit/cloudflare"

[site]
bucket = ".svelte-kit/cloudflare"
