name = "symbaroum"
compatibility_date = "2024-02-13"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "bun run build"
