name = "symbaroum"
compatibility_date = "2024-02-13"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".svelte-kit/output/client"

[env.production]
name = "symbaroum-prod"
routes = ["symbaroum.imperiali.com.br/*"]

[env.staging]
name = "symbaroum-staging"
routes = ["staging.symbaroum.imperiali.com.br/*"]
