name = "symbaroum"
compatibility_date = "2024-02-13"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".svelte-kit/output/client"

[build.upload]
format = "modules"

[env.production]
name = "symbaroum-prod"

[env.staging]
name = "symbaroum-staging"
